from pydantic import BaseModel

from app.bi.operations import OperationsResult, analyze_operations
from app.bi.pipeline import PipelineResult, analyze_pipeline
from app.bi.revenue import RevenueResult, analyze_revenue
from app.bi.sectors import SectorResult, analyze_sector_performance
from app.canonical.models import CanonicalDeal, CanonicalWorkOrder


class LeadershipUpdateResult(BaseModel):
    pipeline: PipelineResult
    operations: OperationsResult
    financial: RevenueResult
    sector_highlights: list[SectorResult]
    risks_and_attention: list[str]


def generate_leadership_update(
    deals: list[CanonicalDeal], work_orders: list[CanonicalWorkOrder]
) -> LeadershipUpdateResult:
    """Pure composition of the other four BI functions — no new data logic.
    `executive_summary` and `key_takeaway` prose (system-prompt §23) are
    generated by the LLM from this structured result, not computed here."""
    pipeline = analyze_pipeline(deals)
    operations = analyze_operations(work_orders)
    financial = analyze_revenue(work_orders)

    sectors = sorted({d.sector for d in deals if d.sector} | {w.sector for w in work_orders if w.sector})
    sector_results = [analyze_sector_performance(deals, work_orders, sector=s) for s in sectors]
    sector_highlights = sorted(
        sector_results, key=lambda s: (s.open_pipeline_value or 0) + (s.revenue_total or 0), reverse=True
    )[:5]

    risks: list[str] = []
    risks.extend(pipeline.caveats)
    risks.extend(operations.caveats)
    risks.extend(financial.caveats)

    return LeadershipUpdateResult(
        pipeline=pipeline,
        operations=operations,
        financial=financial,
        sector_highlights=sector_highlights,
        risks_and_attention=risks,
    )
